import Head from 'next/head'
import NavBar from '../Components/Global/Home/NavBar'
import Hero from '../Components/Private/Home/Hero'
import Media from '../Components/Private/Home/Media'
import Path from '../Components/Private/Home/Path'
import Phylosophy from '../Components/Private/Home/Phylosophy'
import Experts from '../Components/Private/Home/Experts'
import Roadmap from '../Components/Private/Home/Roadmap'
import Feedback from '../Components/Private/Home/Feedback'
import Join from '../Components/Global/Home/Join'
import NFT from '../Components/Private/Home/NFT'
import Axie from '../Components/Private/Home/Axie'
import Register from '../Components/Private/Home/Register'
import Footer from '../Components/Private/Home/Footer'
export default function Home() {
  return (
    <>
      <Head>
        <title>Crypto University</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col'>
        <NavBar/>
        <Hero/>
        <Media/>
        <Path/>
        <Phylosophy/>
        <Experts/>
        <Roadmap/>
        <Feedback/>
        <Join txt="Upcoming Events"/>
        <NFT/>
        <Axie/>
        <Join txt="Register now"/>
        <Register/>
        <Footer/>
      </main>
    </>
  )
}
